export const WEB_COLOR_BLACK = '#000000'
export const WEB_COLOR_OXFORDBLUE = '#14213d'
export const WEB_COLOR_ORANGEWEB = '#fca311'
export const WEB_COLOR_PLATINUM = '#e5e5e5'
export const WEB_COLOR_WHITE = '#ffffff'
export const WEB_COLOR_DARK_HOVER = '#ffffff4d'