// === holiday ===
export const GET_HOLIDAY = 'GET_HOLIDAY'
export const GET_HOLIDAY_SUCCESS = 'GET_HOLIDAY_SUCCESS'
export const GET_HOLIDAY_FAILURE = 'GET_HOLIDAY_FAILURE'
export const RESET_HOLIDAY = 'RESET_HOLIDAY'

// === weather ===
export const GET_WEATHER = 'GET_WEATHER'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE'
export const RESET_WEATHER = 'RESET_WEATHER'